---
title: "abstract"
author:
  - "Marleen Fox"
  - "Carys Artemis Lamm"
  - "Lara Senger"
  - "Luisa von Rhein"
  - "Mino Wittemann"
date: today
date-format: "D. MMMM YYYY"
format:
  pdf:
    papersize: a4
    fontsize: 12pt
    number-sections: true
  html:
    fontsize: 12pt
    number-sections: true
bibliography: literatur.bib
csl: apa7.csl
---

**GitHub Repository:** <https://github.com/MissDoctrix/Statistik-A2.git>\
**Für die Abgabe aktueller GitHub Hash:** b5fd0e2ce7a263133021c16fa0c8c2c1270d65d0

## Einleitung

## Literaturübersicht

Es stehen zwei Fragen im Fokus der Literaturrecherche: Erstens, was sind Nutzendenanforderungen an KI als Werkzeug zur Unterstützung bei der Detektion von Misinformation auf Social Media? Zweitens, wie gehen Personen in diesem Kontext mit unterschiedlichen Feedback-Arten um?

Bei der folgenden Betrachtung wurde @openai2025chatgpt genutzt, um die Formulierungen zu präzisieren und die Rechtschreibung zu kontrollieren.

Einen ersten Einblick in den wissenschaftlichen Forschungsstand und in die Thematik bieten @szczepanski_new_2021. Ihre Arbeit präsentiert eine Erklärungsmethode, mit der deep learning Fake‑News-Modelle nachvollziehbarer werden, indem es die Textstellen hervorhebt, die das Urteil am stärksten beeinflussen. Diese Untersuchung bietet dabei einen Ansatz für die Frage, wie die Ausgabe von KI Werkzeuge gestaltet werden kann, allerdings beinhaltet die Arbeit keine Untersuchung mit verschiedenen Nutzergruppen und ihrem Feedback.

Ähnlichen Einblick bietet @reis_explainable_2019, deren Arbeit ebenfalls die Erklärbarkeit von KI Modellen zur Fake-News-Detektion fokussiert. Durch Verwendung unterschiedlichen Daten versucht das Modell eine ganzheitliche Bewertung zu erreichen und diese nachvollziehbar für Nutzende zu machen, indem das System hervorhebt, welche Merkmale am meisten zu einer Entscheidung betragen. Allerdings liegt auch hier keine direkte Nutzerforschung vor, die Bedürfnisse der Nutzenden werden angenommen ohne empirische Tests.

Eine andere Arbeit von @shu_defend_2019 evaluiert in einer Nutzendenstudie, wie gut Erklärungen und Kommentare bezüglich der Entscheidung einer KI, was ob Nachrichteninhalte Fake News sind, verstanden werden. Dies sind wichtige Orientierungspunkte für die Forschungsfragen. Jedoch untersucht die Arbeit nicht weitergehend, wie unterschiedliche Feedbackformen von den Nutzenden bewertet werden und wie sehr ihnen Vertrauen entgegen gebracht wird.

Die drei genannten Forschungsarbeiten bieten einen ersten Ansatz, sich mit dem Themenfeld vertraut zu machen. Jedoch müssen mehr wissenschaftliche Veröffentlichungen mit dem Schwerpunkt auf Wahrnehmung und Beurteilung unterschiedlicher Feedbacksysteme durch die Nutzenden herangezogen werden, die zudem den Fokus aus Nutzendentests legen und diese Untersuchungen vergleichen. Ebenso sind mehr Arbeiten zu suchen, die empirisch untersuchen, welche Anforderungen durch die Nutzenden gestellt werden und ob sich diese in bestehenden Modellen bereits wiederfinden.

## Methode

### Qualitative Methode

Um sich der Frage anzunähern, welche Anforderungen Nutzende an eine KI-Anwendung zur Unterstützung bei der Erkennung von Misinformation auf Social Media stellen, haben wir die qualitative Forschungsmethode des Interviews gewählt. Personeninterviews bieten die Möglichkeit, von den Nutzenden ausgehende Themen herauszuarbeiten und diese in weiteren Schritten näher zu untersuchen. Durch offen gestellte Fragen können Befragte eigene Gedanken einbringen und für sie wichtige Themen benennen, welche bei vorgegebenen Fragen nicht erfasst werden können. Statt die Themen der Nutzenden anzunehmen, werden diese durch die Interviews erfasst und im Folgenden genutzt, um sich der Forschungsfrage anzunähern.

Wir haben für die Stichprobe junge Erwachsene aus unserem näheren Umfeld gesucht, welche sociale Medien nutzen und bereits mit künstlicher Intelligenz in Berührung gekommen sind. In Form eines Leitfaden-Interviews haben wir die Personen zu ihren Vorerfahrungen, zu ihrem social media Konsum und zu ihrer Einstellung, welche Eigenschaften eine KI-Anwendung haben sollte, die den User über detektierte Misinformation informiert. Die Interviews würde über eine Handy-Applikation lokal auf dem Gerät aufgezeichnet. Die Transkripte wurden von einer ersten Person mit Unterstützung des Transkribtionsprogrammes @whispertranscribe2025 niedergeschrieben und von einer zweiten Person korrigiert und formatiert.

Zur Analyse würde die thematische Analyse in sechs Phasen genutzt. Dabei wurde im Programm Excel der @microsoft_excel_2024 eine Tabelle angelegt, um

## Ergebnisse

| Name | Definition | Textstelle |
|:-----------------------|:-----------------------|:-----------------------|
| Barrierefreiheit | Die Barrierefreiheit beschreibt den Anspruch, dass die Gestaltung der Detektion allen Menschen eine gleichberechtigte und selbstständige Nutzung ermöglicht, unabhängig von individuellen Einschränkungen. | „Also, es muss auf jeden Fall einfach zu bedienen sein \[…\]“ (TN_1, Zeile 75). |
| Verfügbarkeit | Unter dem Kriterium der Verfügbarkeit wird verstanden, dass die KI-Anwendung allen Nutzer\*innen jederzeit und unter gleichen Bedingungen zugänglich ist. | „Also, es muss auf jeden Fall \[…\] für jeden gleich verfügbar sein“ (TN_1, Zeile 75). |
| erfassbare Aufbereitung | Die erfassbare Aufbereitung beschreibt den Anspruch, Informationen visuell so zu gestalten, dass sie schnell, klar und inhaltlich korrekt wahrgenommen und verstanden werden können. | „Und genau, mit einfach kommt natürlich auch sprachlich, dass man es versteht und hatte ich gesagt, dass es schnell sein soll, also dass man sehr schnell versteht, was das Ergebnis von der KI ist. Also wenn das jetzt das einschätzt, dass es praktisch am Anfang direkt einmal sagt, das ist richtig, oder das ist falsch, \[...\]“ (TN_1, Zeile 83 - 86). |
| Einsehbarkeit der Quellen | Die Einsehbarkeit der Quellen beschreibt den Anspruch, dass alle verwendeten Informationsquellen klar benannt, zugänglich und auf ihre Richtigkeit überprüfbar sind. | „Das Einzige, was ich vielleicht finde, ist, dass man die Anforderungen an Quellen oder so was noch hinzufügen könnte, dass man halt sagt, ja, woher hast du das oder wie bist du darauf gekommen?“ (TN_1, Zeile 123 - 125) |
| Beständigkeit der Detektionsergebnisse | Unter Beständigkeit der Detektionsergebnisse wird verstanden, dass die Ergebnisse der Misinformations-Detektion konsistent und unabhängig von der Interaktion mit dem User bleiben. | „Und deswegen finde ich es glaube ich eigentlich besser, wenn man wirklich nur die Einschätzung an sich hat, die dann halt feststeht. Und nicht so, weil, also ich habe das Gefühl, dass man sonst mit der KI ins Diskutieren kommt“ (TN_1, Zeile 120 - 122). |
| personenunabhängige Detektion | Die personenunabhängige Detektion beschreibt den Anspruch, dass die Erkennung von Desinformation ohne Einbezug personenbezogene Daten erfolgt. | „Naja, es dürfte halt nicht auf die Leute zugeschnitten sein im Idealfall \[…\]“ (TN_2, Zeile 56). |
| politischen Unabhängigkeit des KI-Tools | Unter politischer Unabhängigkeit wird der Anspruch verstanden, dass die Detektionsanwendung frei von parteipolitischen Einflüssen agiert und ausschließlich auf Grundlage neutraler, objektiver Kriterien Inhalte auf Desinformation prüft und bewertet. | „Es müsste halt sehr unabhängig programmiert sein, dass keine Lobbys oder so damit entwickeln, die halt vielleicht extra falsche Formationen verstreuen wollen“ (TN_2, Zeile 57 - 59). |

: Analyseergebnisse der Interviews {#tbl-analyse}

## Diskussion

## Code of Conduct {.unnumbered}

Als Arbeitsgruppe verpflichten wir uns einem gemeinsamen Verhaltenskodex, der den Anforderungen wisschenschaftlicher Forschung und respektvollen Umgang entspricht. Dieser bildet die Grundlage für die Zusammenarbeit und beinhaltet folgende Punkte:

Wir begegenen einander offen und respektvoll. Konstruktives Feedback wird wertgeschätzend geäußert, aufgenommen und besprochen. Dabei sind unterschiedliche Perspektiven und Meinungen willkommen und werden als zur Zusammenarbeit gehörend betrachtet. Entsprechend wird sich im Konfliktfall gemeinsam bemüht wird, eine zufriedenstellende Lösung zu finden. Die Mitglieder werden als gleichberechtig angesehen und behandelt.

Es wird eine ausgewogene Aufteilung der Arbeitslast angestrebt, die die Stärken und Schwächen der einzelnen Mitgleider berücksichtigt. Folglich verpflichten wir uns zu einer offenen und direkten Kommunikation. Im Falle möglicher Verzögerungen, Probleme oder unerwarteter Auslastungen wird frühzeitig kommuniziert und sich gegenseitig unterstützt.

Wir verpflichten uns der Einhaltung wissenschaftlicher Standards, mit besonderer Umsicht gegenüber erhobener, personenbezogener Daten und der Wahrung ihrer Vertraulichkeit. Ebenso wird streng auf sorgfältigen Recherche und korrekte Zitation geachtet. Die verantwortungsvolle Nutzung von AI Tools erfolgt transparent mit Beschreibung und Kennzeichnung der Nutzung.

## Literaturverzeichnis {.unnumbered}
